package simh

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hashicorp/packer-plugin-sdk/multistep"
	"github.com/hashicorp/packer-plugin-sdk/packer"
)

func testCommandFileState(config *Config) *multistep.BasicStateBag {
	state := new(multistep.BasicStateBag)
	state.Put("config", config)
	state.Put("ui", &packer.MockUi{})
	state.Put("console_port", 4001)
	state.Put("http_ip", "127.0.0.1")
	state.Put("http_port", 8080)
	return state
}

func TestStepCreateCommandFile_BasicGenerated(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	action := step.Run(context.Background(), state)

	if action != multistep.ActionContinue {
		if err, ok := state.GetOk("error"); ok {
			t.Fatalf("expected ActionContinue, got error: %s", err)
		}
		t.Fatal("expected ActionContinue")
	}

	cmdPath := state.Get("command_file_path").(string)
	content, err := os.ReadFile(cmdPath)
	if err != nil {
		t.Fatal(err)
	}

	text := string(content)

	// Check header.
	if !strings.Contains(text, "; Generated by packer-plugin-simh") {
		t.Error("missing header comment")
	}

	// Check console config: SIMH needs two separate SET CONSOLE TELNET= commands.
	if !strings.Contains(text, "SET CONSOLE TELNET=127.0.0.1:4001\n") {
		t.Error("missing console telnet host:port config")
	}
	if !strings.Contains(text, "SET CONSOLE TELNET=BUFFERED\n") {
		t.Error("missing console telnet BUFFERED config")
	}

	// Check console log.
	if !strings.Contains(text, "SET CONSOLE LOG=") {
		t.Error("missing console log config")
	}

	// Check BOOT CPU.
	if !strings.Contains(text, "BOOT CPU") {
		t.Error("missing BOOT CPU")
	}

	// Check QUIT.
	if !strings.Contains(text, "QUIT") {
		t.Error("missing QUIT")
	}

	// QUIT should be the last non-empty line.
	lines := strings.Split(strings.TrimSpace(text), "\n")
	lastLine := strings.TrimSpace(lines[len(lines)-1])
	if lastLine != "QUIT" {
		t.Errorf("expected QUIT as last line, got %q", lastLine)
	}
}

func TestStepCreateCommandFile_CPUConfig(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		CPUType:            "MicroVAX",
		Memory:             "128M",
		CPUOptions:         []string{"CONHALT"},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	if !strings.Contains(text, "SET CPU MicroVAX") {
		t.Error("missing SET CPU MicroVAX")
	}
	if !strings.Contains(text, "SET CPU 128M") {
		t.Error("missing SET CPU 128M")
	}
	if !strings.Contains(text, "SET CPU CONHALT") {
		t.Error("missing SET CPU CONHALT")
	}
}

func TestStepCreateCommandFile_DiskAttachments(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		DiskAttachments: []DiskAttachment{
			{
				Device:      "RQ0",
				Path:        "system.dsk",
				SetCommands: []string{"RD54"},
			},
		},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	if !strings.Contains(text, "SET RQ0 RD54") {
		t.Error("missing SET RQ0 RD54")
	}
	if !strings.Contains(text, "ATTACH RQ0") {
		t.Error("missing ATTACH RQ0")
	}
}

func TestStepCreateCommandFile_NetworkDevice(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		NetworkDevice: &NetworkDevice{
			Device:     "XQ",
			MAC:        "08-00-2B-AA-BB-CC",
			AttachType: "nat:tcp=2222:10.0.2.15:22",
		},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	if !strings.Contains(text, "SET XQ MAC=08-00-2B-AA-BB-CC") {
		t.Error("missing SET XQ MAC")
	}
	if !strings.Contains(text, "ATTACH XQ nat:tcp=2222:10.0.2.15:22") {
		t.Error("missing ATTACH XQ")
	}
}

func TestStepCreateCommandFile_ExternalCommandFile(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	// Create external command file.
	extFile := filepath.Join(t.TempDir(), "external.simh")
	_ = os.WriteFile(extFile, []byte("SET CPU MicroVAX\nBOOT CPU\n"), 0644)

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		CommandFile:        extFile,
		// These should be ignored when command_file is set.
		CPUType: "SomeOtherCPU",
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	// Should contain console config (two separate SET CONSOLE TELNET= commands).
	if !strings.Contains(text, "SET CONSOLE TELNET=") || !strings.Contains(text, "SET CONSOLE TELNET=BUFFERED") {
		t.Error("missing console config in external command file mode")
	}

	// Should contain external file contents.
	if !strings.Contains(text, "SET CPU MicroVAX") {
		t.Error("missing external file content")
	}

	// Should NOT contain the ignored CPU type.
	if strings.Contains(text, "SomeOtherCPU") {
		t.Error("ignored config field should not appear")
	}

	// Should end with QUIT.
	if !strings.Contains(text, "QUIT") {
		t.Error("missing QUIT")
	}
}

func TestStepCreateCommandFile_ConsoleLogDisabled(t *testing.T) {
	dir := t.TempDir()
	falseVal := false

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &falseVal,
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	if strings.Contains(text, "SET CONSOLE LOG=") {
		t.Error("console log should not be present when disabled")
	}
}

func TestStepCreateCommandFile_PathWithSpaces(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	// Console log path should be quoted.
	if !strings.Contains(text, "SET CONSOLE LOG=\"") {
		t.Error("expected quoted console log path for path with spaces")
	}
}

func TestStepCreateCommandFile_DiskPathWithQuoteRejected(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		DiskAttachments: []DiskAttachment{
			{
				Device: "RQ0",
				Path:   `disk"file.dsk`,
			},
		},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	action := step.Run(context.Background(), state)

	if action != multistep.ActionHalt {
		t.Error("expected ActionHalt for path with double quotes")
	}
}

func TestStepCreateCommandFile_SimhArgs(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		SimhArgs:           []string{"SET THROTTLE 50%"},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	if !strings.Contains(text, "SET THROTTLE 50%") {
		t.Error("missing simh_args content")
	}
}

func TestStepCreateCommandFile_TemplateInterpolation(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		DiskAttachments: []DiskAttachment{
			{
				Device: "RQ0",
				Path:   "{{ .OutputDir }}/system.dsk",
			},
		},
	}

	state := testCommandFileState(config)
	state.Put("iso_path", "/tmp/test.iso")

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	// Check that {{ .OutputDir }} was interpolated.
	if strings.Contains(text, "{{ .OutputDir }}") {
		t.Error("template variable was not interpolated")
	}
	expectedPath := filepath.Join(dir, "system.dsk")
	if !strings.Contains(text, expectedPath) {
		t.Errorf("expected interpolated path %s in command file", expectedPath)
	}
}

func TestStepCreateCommandFile_SectionOrder(t *testing.T) {
	dir := t.TempDir()
	trueVal := true

	config := &Config{
		OutputDirectory:    dir,
		VMName:             "test-vm",
		ConsoleBindAddress: "127.0.0.1",
		ConsoleLog:         &trueVal,
		CPUType:            "MicroVAX",
		SimhArgs:           []string{"SET THROTTLE 50%"},
		NetworkDevice: &NetworkDevice{
			Device:     "XQ",
			AttachType: "nat:tcp=2222:10.0.2.15:22",
		},
		DiskAttachments: []DiskAttachment{
			{
				Device: "RQ0",
				Path:   "disk.dsk",
			},
		},
	}

	state := testCommandFileState(config)

	step := &stepCreateCommandFile{}
	step.Run(context.Background(), state)

	cmdPath := state.Get("command_file_path").(string)
	content, _ := os.ReadFile(cmdPath)
	text := string(content)

	// Verify ordering: console < cpu < simh_args < network < disk < boot < quit
	consoleIdx := strings.Index(text, "SET CONSOLE TELNET=")
	cpuIdx := strings.Index(text, "SET CPU MicroVAX")
	argsIdx := strings.Index(text, "SET THROTTLE")
	netIdx := strings.Index(text, "ATTACH XQ")
	diskIdx := strings.Index(text, "ATTACH RQ0")
	bootIdx := strings.Index(text, "BOOT CPU")
	quitIdx := strings.Index(text, "QUIT")

	if consoleIdx >= cpuIdx {
		t.Error("console config should come before CPU config")
	}
	if cpuIdx >= argsIdx {
		t.Error("CPU config should come before simh_args")
	}
	if argsIdx >= netIdx {
		t.Error("simh_args should come before network config")
	}
	if netIdx >= diskIdx {
		t.Error("network config should come before disk attachments")
	}
	if diskIdx >= bootIdx {
		t.Error("disk attachments should come before BOOT CPU")
	}
	if bootIdx >= quitIdx {
		t.Error("BOOT CPU should come before QUIT")
	}
}
