package simh

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/hashicorp/packer-plugin-sdk/multistep"
	"github.com/hashicorp/packer-plugin-sdk/packer"
	"github.com/hashicorp/packer-plugin-sdk/template/interpolate"
)

type stepCreateCommandFile struct{}

func (s *stepCreateCommandFile) Run(ctx context.Context, state multistep.StateBag) multistep.StepAction {
	config := state.Get("config").(*Config)
	ui := state.Get("ui").(packer.Ui)

	// Populate template data from state.
	td := populateTemplateData(config, state)

	// Set template data on the interpolation context.
	config.ctx.Data = &td

	consolePort := state.Get("console_port").(int)

	var b strings.Builder

	// Section 1 — Header
	b.WriteString("; Generated by packer-plugin-simh — do not edit\n")

	// Section 2 — Console Configuration
	//
	// SIMH requires these as two separate SET CONSOLE TELNET= commands.
	// The combined form "TELNET=host:port,BUFFERED" is parsed as a port
	// option list and rejected ("No settable parameters").
	b.WriteString("\n; Console configuration\n")
	fmt.Fprintf(&b, "SET CONSOLE TELNET=%s:%d\n",
		config.ConsoleBindAddress, consolePort)
	b.WriteString("SET CONSOLE TELNET=BUFFERED\n")

	if *config.ConsoleLog {
		logPath := filepath.Join(config.OutputDirectory, config.VMName+".console.log")
		fmt.Fprintf(&b, "SET CONSOLE LOG=%s\n", quotePath(logPath))
	}

	if config.CommandFile != "" {
		// External command file mode.
		content, err := os.ReadFile(config.CommandFile)
		if err != nil {
			err := fmt.Errorf("error reading command_file '%s': %s", config.CommandFile, err)
			state.Put("error", err)
			ui.Error(err.Error())
			return multistep.ActionHalt
		}

		// Interpolate file contents (Pass 2).
		rendered, err := interpolate.Render(string(content), &config.ctx)
		if err != nil {
			err := fmt.Errorf("error interpolating command_file contents: %s", err)
			state.Put("error", err)
			ui.Error(err.Error())
			return multistep.ActionHalt
		}

		b.WriteString("\n")
		b.WriteString(rendered)
		if !strings.HasSuffix(rendered, "\n") {
			b.WriteString("\n")
		}
	} else {
		// Generated command file mode.
		if err := s.writeGeneratedContent(config, &b, &td); err != nil {
			state.Put("error", err)
			ui.Error(err.Error())
			return multistep.ActionHalt
		}
	}

	// Section 8 — Quit (always last)
	b.WriteString("\n; Auto quit\n")
	b.WriteString("QUIT\n")

	// Resolve disk paths and store in state for artifact.
	diskPaths, err := s.resolveDiskPaths(config, &td)
	if err != nil {
		state.Put("error", err)
		ui.Error(err.Error())
		return multistep.ActionHalt
	}
	state.Put("disk_paths", diskPaths)

	// Write the command file.
	cmdFilePath := filepath.Join(config.OutputDirectory, config.VMName+".simh")

	ui.Say(fmt.Sprintf("Writing SIMH command file: %s", cmdFilePath))
	if err := os.WriteFile(cmdFilePath, []byte(b.String()), 0644); err != nil {
		err := fmt.Errorf("error writing command file: %s", err)
		state.Put("error", err)
		ui.Error(err.Error())
		return multistep.ActionHalt
	}

	if config.PackerDebug {
		ui.Say(fmt.Sprintf("Command file contents:\n%s", b.String()))
	}

	state.Put("command_file_path", cmdFilePath)
	return multistep.ActionContinue
}

func (s *stepCreateCommandFile) writeGeneratedContent(config *Config, b *strings.Builder, td *templateData) error {
	// Section 3 — CPU Configuration
	if config.CPUType != "" || config.Memory != "" || len(config.CPUOptions) > 0 {
		b.WriteString("\n; CPU configuration\n")
		if config.CPUType != "" {
			fmt.Fprintf(b, "SET CPU %s\n", config.CPUType)
		}
		if config.Memory != "" {
			fmt.Fprintf(b, "SET CPU %s\n", config.Memory)
		}
		for _, opt := range config.CPUOptions {
			fmt.Fprintf(b, "SET CPU %s\n", opt)
		}
	}

	// Section 4 — Extra SIMH Commands
	if len(config.SimhArgs) > 0 {
		b.WriteString("\n; Additional SIMH commands\n")
		for _, arg := range config.SimhArgs {
			rendered, err := interpolate.Render(arg, &config.ctx)
			if err != nil {
				return fmt.Errorf("error interpolating simh_args: %s", err)
			}
			b.WriteString(rendered + "\n")
		}
	}

	// Section 5 — Network Configuration
	if config.NetworkDevice != nil || len(config.NetworkCommands) > 0 {
		b.WriteString("\n; Network configuration\n")

		if config.NetworkDevice != nil {
			nd := config.NetworkDevice
			if nd.MAC != "" {
				fmt.Fprintf(b, "SET %s MAC=%s\n", nd.Device, nd.MAC)
			}
			for _, sc := range nd.SetCommands {
				rendered, err := interpolate.Render(sc, &config.ctx)
				if err != nil {
					return fmt.Errorf("error interpolating network_device set_commands: %s", err)
				}
				fmt.Fprintf(b, "SET %s %s\n", nd.Device, rendered)
			}
			renderedAttach, err := interpolate.Render(nd.AttachType, &config.ctx)
			if err != nil {
				return fmt.Errorf("error interpolating network_device attach_type: %s", err)
			}
			fmt.Fprintf(b, "ATTACH %s %s\n", nd.Device, renderedAttach)
		}

		for _, nc := range config.NetworkCommands {
			rendered, err := interpolate.Render(nc, &config.ctx)
			if err != nil {
				return fmt.Errorf("error interpolating network_commands: %s", err)
			}
			b.WriteString(rendered + "\n")
		}
	}

	// Section 6 — Disk Attachments
	for _, da := range config.DiskAttachments {
		fmt.Fprintf(b, "\n; Disk: %s\n", da.Device)

		for _, sc := range da.SetCommands {
			rendered, err := interpolate.Render(sc, &config.ctx)
			if err != nil {
				return fmt.Errorf("error interpolating disk set_commands: %s", err)
			}
			fmt.Fprintf(b, "SET %s %s\n", da.Device, rendered)
		}

		renderedPath, err := interpolate.Render(da.Path, &config.ctx)
		if err != nil {
			return fmt.Errorf("error interpolating disk path: %s", err)
		}

		resolvedPath := resolveDiskPath(renderedPath, config.OutputDirectory)

		// Validate no double quotes in path.
		if strings.Contains(resolvedPath, "\"") {
			return fmt.Errorf("disk path contains double quotes which SIMH cannot handle: %s", resolvedPath)
		}

		// Create parent directories for relative paths or paths under output_directory.
		if err := ensureParentDir(resolvedPath, config.OutputDirectory); err != nil {
			return err
		}

		quoted := quotePath(resolvedPath)
		if da.Options != "" {
			renderedOpts, err := interpolate.Render(da.Options, &config.ctx)
			if err != nil {
				return fmt.Errorf("error interpolating disk options: %s", err)
			}
			fmt.Fprintf(b, "ATTACH %s %s %s\n", da.Device, quoted, renderedOpts)
		} else {
			fmt.Fprintf(b, "ATTACH %s %s\n", da.Device, quoted)
		}
	}

	// Section 7 — Boot Command
	b.WriteString("\n; Boot\n")
	b.WriteString("BOOT CPU\n")

	return nil
}

// resolveDiskPaths resolves all disk attachment paths and returns absolute paths.
func (s *stepCreateCommandFile) resolveDiskPaths(config *Config, td *templateData) ([]string, error) {
	if config.CommandFile != "" {
		// When using external command file, we don't know the disk paths.
		return nil, nil
	}

	var paths []string
	for _, da := range config.DiskAttachments {
		rendered, err := interpolate.Render(da.Path, &config.ctx)
		if err != nil {
			return nil, fmt.Errorf("error resolving disk path: %s", err)
		}
		resolved := resolveDiskPath(rendered, config.OutputDirectory)
		paths = append(paths, resolved)
	}
	return paths, nil
}

func (s *stepCreateCommandFile) Cleanup(state multistep.StateBag) {}

// populateTemplateData creates a templateData struct from config and state bag.
func populateTemplateData(config *Config, state multistep.StateBag) templateData {
	td := templateData{
		Name:      config.VMName,
		OutputDir: config.OutputDirectory,
	}

	if httpIP, ok := state.GetOk("http_ip"); ok {
		td.HTTPIP = httpIP.(string)
	}
	if httpPort, ok := state.GetOk("http_port"); ok {
		td.HTTPPort = httpPort.(int)
	}
	if isoPath, ok := state.GetOk("iso_path"); ok {
		p := isoPath.(string)
		// Make the ISO path absolute so that when it is used in
		// disk_attachments via {{ .ISOPath }}, resolveDiskPath won't
		// incorrectly join it with the output directory.
		if !filepath.IsAbs(p) {
			if abs, err := filepath.Abs(p); err == nil {
				p = abs
			}
		}
		td.ISOPath = p
	}
	if hostPort, ok := state.GetOk("commHostPort"); ok {
		td.HostPort = hostPort.(int)
	}
	if config.Type == "ssh" {
		td.SSHPublicKey = string(config.SSHPublicKey)
		td.GuestPort = config.Port()
	}

	return td
}

// resolveDiskPath resolves a disk path. If not absolute, joins with outputDir.
func resolveDiskPath(path, outputDir string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(outputDir, path)
}

// quotePath wraps a path in double quotes if it contains whitespace.
func quotePath(path string) string {
	if strings.ContainsAny(path, " \t") {
		return fmt.Sprintf("\"%s\"", path)
	}
	return path
}

// ensureParentDir creates parent directories for paths under or relative to
// outputDir.
func ensureParentDir(resolvedPath, outputDir string) error {
	if strings.HasPrefix(resolvedPath, outputDir) {
		dir := filepath.Dir(resolvedPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("error creating parent directory for disk path: %s", err)
		}
	} else {
		log.Printf("[DEBUG] Disk path '%s' is outside output directory; not creating parent dirs", resolvedPath)
	}
	return nil
}
